name: Custom github workflow
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: Farhan_First_project_with_github_action
  LEARNING: Github_action_learning

jobs:
  myexamplejob:
    steps:
      - run: echo "Checkout the repo"
      - name: Checkout Repo
        uses: actions/checkout@v4
      - run: printenv
      - run: echo "These are the environment variable with project name ${{ env.PROJECT_NAME}} and learning title is ${{ env.LEARNING }}"